name: Go
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/go-build/
            /home/runner/go/pkg/mod/
          key: GO_MOD_CACHE
      - name: Requirements
        run: sudo apt-get install upx-ucl
      - name: Build
        run: ./build.sh
      - name: Upload build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build_artifacts
          path: http-mock
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.cache/go-build/
            /home/runner/go/pkg/mod/
          key: GO_MOD_CACHE
      - name: test
        run: go test -timeout 360s -coverprofile=cover.out -covermode atomic github.com/slytomcat/http-mock --race -v
      - name: Format coverage
        run: go tool cover -html=cover.out -o coverage.html
      - name: Upload coverage to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage_artifacts
          path: coverage.html
  push:
    needs: [build, test]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build_artifacts
      - name: draft new release and upload assets
        env: 
          GH_TOKEN: ${{ secrets.ACTION_TOKEN }}
        run: |
          gh release create "$(git branch --show-current)-$(git rev-parse --short HEAD)" ./http-mock

